### PR TITLE
Move example notebooks to documentation

### PR DESCRIPTION
**Pull request by rrjbca**
## Description
Make the existing ipython notebooks for the examples part of the documentation, rendering them using the [`nbsphinx`](https://nbsphinx.readthedocs.io/) extension. This should make them more visible to the user as they are linked from the front page of the documentation and do not need to be viewed through GitHub. The new documentation can be viewed here:

- [Documentation front page](https://skypy--354.org.readthedocs.build/en/354/)
- [Abundance matching notebook](https://skypy--354.org.readthedocs.build/en/354/examples/abundance_matching.html)
- [Gravitational wave rate notebook](https://skypy--354.org.readthedocs.build/en/354/examples/gravitational_wave_rates.html)
- [MCCL galaxies notebook](https://skypy--354.org.readthedocs.build/en/354/examples/mccl_galaxies.html)

## Checklist
- [x] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/master/CONTRIBUTING.md)
- [ ] ~Write unit tests~
- [ ] Write documentation strings
- [x] Assign someone from your working team to review this pull request
- [x] Assign someone from the infrastructure team to review this pull request

### CODE REVIEW

**Comment by ntessore** [comment]
Looks good, although I think for the sake of visibility, I would prefer these to be under a separate "Examples" page under "Getting started" in the documentation, which should ideally mention the "examples" folder where the configs can be found. Then there can also be a highly visible link at the top of the GitHub readme pointing straight at that examples page.

**Comment by ntessore** [comment]
Next step could then be moving the blurb about installation from the GitHub readme into "Installation" under "Getting started", and we point to there from the GitHub readme? Because I think it is important that a new user is presented with very little noise in the first 30 seconds, and that "here are our examples" is the first thing they notice.

**Comment by Lucia-Fonseca** [comment]
Agreed with @ntessore.

> Next step could then be moving the blurb about installation from the GitHub readme into "Installation" under "Getting started", and we point to there from the GitHub readme? Because I think it is important that a new user is presented with very little noise in the first 30 seconds, and that "here are our examples" is the first thing they notice.

**Comment by rrjbca** [comment]
Closing in favour of using sphinx-gallery for examples as in #385

**Pull request closed without merging**
