### PR TITLE
mirror examples to repository

### PR DESCRIPTION
**Pull request by ntessore**
This GitHub workflow should update the skypyproject/examples repository every night, mirroring all branches and tags of our library repository.

### CODE REVIEW

**Comment by ntessore** [comment]
I think there is no way for me to test that this works before it is merged?

**Review by rrjbca — COMMENTED** [review]
Not sure what  `on: workflow_dispatch` is doing here, but rather than mirroring on a schedule wouldn't it make sense to trigger on push or release like you had originally? You can also trigger e.g. only when the examples are changed on master:

```
on:
  push:
    branches:
    - master
    paths:
    - 'examples/**'
```

**Comment by ntessore** [comment]
> Not sure what `on: workflow_dispatch` is doing here

One can manually trigger a `workflow_dispatch` which would be useful if the README on the examples master branch is edited and the changes are to be deployed to all other branches and tags before the next regular trigger.

**Review by rrjbca — APPROVED** [review]
Looks good, will merge now

**Pull request merged**
