### PR TITLE
DOC: Remove Docstring examples in power_spectrum

### LINKED ISSUE #446: Remove docstring examples for power spectrum
## Description
The examples section in the docstrings for the power spectrum module are trivial and run as part of the tests unnecessarily. 
More complex examples would appear in our documentation [readthedocs](https://skypy--445.org.readthedocs.build/en/445/examples/index.html).

### PR DESCRIPTION
**Pull request by Lucia-Fonseca**
## Description
This PR removes the docstring examples sections. Merging this PR closes #446. 
## Checklist
- [x] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/main/CONTRIBUTING.rst)
- [ ] Write unit tests
- [x] Write documentation strings
- [x] Assign someone from your working team to review this pull request
- [x] Assign someone from the infrastructure team to review this pull request

### CODE REVIEW

**Comment by jucordero** [comment]
Isn't this similar to #429 ?

**Comment by Lucia-Fonseca** [comment]
> #429

I thought this is only for the galaxy module. I couldn't find any issue related with that PR.

**Comment by Lucia-Fonseca** [comment]
@rrjbca @ntessore should I do this here or as part of #429 ?
> > #429
> 
> I thought this is only for the galaxy module. I couldn't find any issue related with that PR.

**Comment by rrjbca** [comment]
Here; it's part of the power spectrum module

**Comment by ntessore** [comment]
> @rrjbca @ntessore should I do this here or as part of #429 ?
> 
> > > #429
> > 
> > 
> > I thought this is only for the galaxy module. I couldn't find any issue related with that PR.

It cannot possibly be part of #429 since that is against the main branch.

**Review by rrjbca — APPROVED** [review]

**Pull request merged**
