### PR TITLE
fix and improve galaxy module docs

### PR DESCRIPTION
**Pull request by ntessore**
## Description

This PR fixes a number of documentation issues in the galaxy module, and improves the overall layout.

## Checklist
- [x] Follow the [Contributor Guidelines](https://github.com/skypyproject/skypy/blob/develop/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ntessore** [comment]
You can check out the documentation using the "giles" details link in the checks.

**Comment by ntessore** [comment]
> Is there a rule how many '-' to make in the docstring?

Yes

**Comment by ntessore** [comment]
> I just saw that there is a typo in the notes of `herbel_redshifts` and ` herbel_luminosities`. There is a `/` instead of `\` in front of `exp`. I don't know how to comment on the lines. There is no '+'.

I didn't change the contents of any docstrings unless it fixed an issue with the build.

**Comment by philipp128** [comment]
> > I just saw that there is a typo in the notes of `herbel_redshifts` and ` herbel_luminosities`. There is a `/` instead of `\` in front of `exp`. I don't know how to comment on the lines. There is no '+'.
> 
> I didn't change the contents of any docstrings unless it fixed an issue with the build.

Yeah, I thought so. Do you mind changing that? Or do we want to find these issues later?

**Comment by ntessore** [comment]
If you write the changes up as suggestions then I can merge them into the PR.

**Comment by philipp128** [comment]
> If you write the changes up as suggestions then I can merge them into the PR.

That's what I meant with no '+'. I don't know how to do anything with these lines. Normally, there appears the '+' if I move the cursor above it.

**Comment by rrjbca** [comment]
> That's what I meant with no '+'. I don't know how to do anything with these lines. Normally, there appears the '+' if I move the cursor above it.

You cannot make suggestions for any line of code in the project, only for lines of code changed by the pull request. Since this pull request deals with fixing warnings rather than typos I'm going to suggest we merge it as is. We are planning a documentation hack as part of out meeting next week to fix typos etc or you can start your own pull request to address these typos. I will try and fix similar warnings in linear and nonlinear while addressing #69.

**Pull request merged**
